### ISSUE TITLE
ViewModel not injected to Widget

### ISSUE THREAD

**Issue by kamilpowalowski** [tomwyr/async-redux-vscode#8]
I think that ViewModel should be already injected into the widget in this setup code. This will save us from one operation that we always do.

**Comment by tomwyr** [comment]
`async_redux` proposes to pass all objects from your view model to widget which makes the widget know nothing about other redux classes. Personally, I dislike this approach and it would be nice to have a flag in settings that makes generated code inject whole view model object as you mentioned and avoid some boilerplate 😄
