### ISSUE TITLE
Barrel file exporting unnecessary files

### ISSUE THREAD

**Issue by kamilpowalowski** [tomwyr/async-redux-vscode#9]
generated barrel file exports:
```
export 'testing_widget.dart';
export 'testing_connector.dart';
export 'testing_view_model.dart';
export 'testing_view_model_factory.dart';
```
I think it should export only testing_connector.dart since the rest of the files are only internal implementations of the Widget, Page and shouldn't be used outside.

**Comment by tomwyr** [comment]
Closed in #18.
